In [1]:
import numpy as np
data1 = [1,3,5,7]
w1 = np.array(data1)
print('w1:',w1)

w1: [1 3 5 7]


In [2]:
array_a = np.arange(10)
print(array_a)
array_b = np.arange(0,1,0.2)
print(array_b)

[0 1 2 3 4 5 6 7 8 9]
[0.  0.2 0.4 0.6 0.8]


In [3]:
array_c = np.linspace(0,1,5)
print("等差一维数组:", array_c)

等差一维数组： [0.   0.25 0.5  0.75 1.  ]


In [4]:
array_d = np.logspace(0,1,5)
print("等比一维数组:",array_d)

等比一维数组: [ 1.          1.77827941  3.16227766  5.62341325 10.        ]


In [6]:
array_i = np.diag([1,2,3,4],k=0)
print(array_i)
array_j = np.diag([1,2,3,4],k=1)
print(array_j)
array_k = np.diag([1,2,3,4],k=-1)
print(array_k)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [7]:
arr = np.random.randint(100, 200, size = (2,4))
print(arr)

[[156 100 113 120]
 [145 111 156 131]]


In [8]:
arr1 = np.random.rand(5)
print(arr1)
arr1 = np.random.rand(4,2)
print(arr1)

[0.71570914 0.7108893  0.35814731 0.01012743 0.87281304]
[[0.11333713 0.99391985]
 [0.90895128 0.16360599]
 [0.37936144 0.59573996]
 [0.90263144 0.68775953]]


In [13]:
np.random.seed(100)

In [14]:
np.random.rand(2,2)

array([[0.54340494, 0.27836939],
       [0.42451759, 0.84477613]])

In [15]:
arr1 = np.random.binomial(10,0.2,(2,4))
print(arr1)

[[0 1 2 3]
 [1 2 4 1]]


In [17]:
arr1 = np.arange(12)
print("arr1:",arr1)
arr2 = arr1.reshape(3,4)
print("arr2:",arr2)

arr1: [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr2: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
arr3 = arr1.reshape(2,-1)
print("arr3:",arr3)

arr3: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [20]:
arr1 = np.arange(6).reshape(3,2)
arr2 = arr1*2
arr3 = np.hstack((arr1,arr2))
print(arr3)

[[ 0  1  0  2]
 [ 2  3  4  6]
 [ 4  5  8 10]]


In [21]:
arr4 = np.vstack((arr1,arr2))
print(arr4)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 0  2]
 [ 4  6]
 [ 8 10]]


In [24]:
arr1 = np.arange(6).reshape(3,2)
print("矩阵:\n",arr1)
arr2 = arr1.T
print("转置矩阵:\n",arr2)

矩阵: [[0 1]
 [2 3]
 [4 5]]
转置矩阵: [[0 2 4]
 [1 3 5]]


In [25]:
arr1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
print("arr1:\n",arr1)
arr2 = np.array([1,2,3])
print("arr2:\n",arr2)
arr3 = arr1 + arr2
print("广播法则之后的结果:\n",arr3)

arr1:
 [[0 0 0]
 [1 1 1]
 [2 2 2]]
arr2:
 [1 2 3]
广播法则之后的结果:
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


In [27]:
arr1 = np.array([1,3,5,7])
arr2 = np.array([2,4,6,8])
arr3 = np.array([True,False,True,False])
result = [(x if z else y) for x,y,z in zip(arr1,arr2,arr3)]
result

[1, 4, 5, 8]

In [28]:
np.where([[True,False],[True,True]],[[1,2],[3,4]],[[9,8],[7,6]])

array([[1, 8],
       [3, 4]])